### ISSUE TITLE
🧃 [Feat] Network 세팅할거다 유진아

### ISSUE THREAD

**Issue by hooni0918** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#16]
## 작업할 브랜치
- `NetworkForldering` 브랜치에서 작업합니다.

## ✔️ To-Do
- [ ] 네트워크 api 파일 생성
- [ ] 네트워크 foundation 생성
- [ ] 네트워크 manager 생성
