### ISSUE TITLE
🧃 [Feat] SearchView API 연결할거다 유진아

### ISSUE THREAD

**Issue by wjdalswl** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#19]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 | <img width="250" alt="스크린샷 2024-05-24 오전 6 08 51" src="https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/109158284/8b8d0638-5416-44c6-b85b-86ac9e61067d">
 

## 작업할 브랜치
- `feat/19-searchView-API` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 🍀 일반 검색 API 연결
- [x] 🍀 필터 검색 API
- [x]  검색결과 없을때 뷰 추가

## 🙋🏻 양해의 말씀..,.
원래 일반검색과 필터검색을 따로 이슈파서 진행하는게 맞지만 제가 내일 저녁 8-9시 시험이라 여러분들 어프로브 받고 다시 이슈파서 작업할 시간이 안될거같아서 한번에 작업해서 올립니다..! 죄송합니다..,
