### ISSUE TITLE
🍎 [Style] 이력서 UI 구현할거다 유진아

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#22]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 | <img src = "https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/80394340/2932c0e2-ee8b-477d-8277-71e74cfa2665" width ="250"> 

## 작업할 브랜치
- `style/22-resume` 브랜치에서 작업합니다.

## ✔️ To-Do
- [ ] 이력서 화면 작업
- [ ] 이력서 추가 바텀시트 작업
- [ ] 이력서 편집 바텀시트 작업
