### ISSUE TITLE
🧃[Feat] 이력서 API 연결한다 유진아

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#28]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 | <img src = "https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/80394340/0a45685d-007b-4220-931f-0eed06124940" width ="250">
## 작업할 브랜치
- `feat/28-resume` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] DTO 설계
- [x] 이력서 조회 API 연결
- [x] 비공개 여부 패치 API 연결
- [x] UI에 데이터 반영
