### ISSUE TITLE
🍎 [Style] 검색뷰 UI 작업할거다 유진아

### ISSUE THREAD

**Issue by wjdalswl** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#6]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 최근 검색어 | <img width="380" alt="스크린샷 2024-05-15 오전 3 50 24" src="https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/109158284/9e7a9e3d-b643-4464-8f0d-e4939c3ecf93"> |
| 검색시 | <img width="380" alt="스크린샷 2024-05-15 오전 3 51 48" src="https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/109158284/7b819120-643c-4bc2-8da0-f046f56ad372">  |
| 검색 결과 x | <img width="380" alt="스크린샷 2024-05-15 오전 3 52 17" src="https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/109158284/9e221e4d-c214-421e-b3dc-62d77e1d16e2"> |

## 작업할 브랜치
- `feat/6-searchViewController-UI` 브랜치에서 작업합니다.

## ✔️ To-Do
- [ ] 검색 textField 커스텀 네비게이션 바로 구현하기
- [ ] userDefault로 최근 검색어 구현하기
- [ ] 검색 결과 cell UI 작업
- [ ] 검색 결과 화면 UI 작업 -> 결과 있는 ver
- [ ] 검색 결과 화면 UI 작업 -> 결과 없는 ver
