### ISSUE TITLE
🍎 [Style] 홈 화면 UI 구현할거다 유진아

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#7]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 | <img src = "https://github.com/NOW-SOPT-APP8-JUMPIT/Jumpit-iOS/assets/80394340/b2a35403-76cc-49bc-b195-be0a3fe58248" width ="250"> 

## 작업할 브랜치
- `style/7-home-ui` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 스크롤뷰 구현
- [x] 탭바 및 네비게이션 바 구현
- [x] 직무별로 보기 부분 구현
- [x] 테마별 모음 부분 구현
- [x] 개발자에게 꼭 필요한 것만! 부분 구현

**Comment by youz2me** [comment]
@wjdalswl 민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어민지야도와줘민지야도와주어
