### ISSUE TITLE
♻️ [Refactor] 컬러 에셋 이름 바꾼다 유진아

### ISSUE THREAD

**Issue by youz2me** [NOW-SOPT-APP8-JUMPIT/Jumpit-iOS#9]
## 작업할 브랜치
- `refactor/9-asset-refactoring` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 컬러 에셋 이름 시스템 경고 없게 변경하기
- [x] 컬러 에셋 폴더링하기
- [x] 아이콘 single scale로 변환
